import Head from "next/head";
import Header from "./shared/header";
import Footer from "./shared/Footer";
import Map from "./shared/Map";
import Queryform from "./shared/Queryform";

function Product() {
  return (
    <div className="services secondary-page container-fluid px-0 contact-us">
      <Head>
        <title>Contact Us</title>
        <meta
          name="description"
          content="Generated by create next app shubham"
        />
        <link
          rel="preload"
          href="../../../public/fonts/GTWalsheimPro-Regular.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Header />
      <section className="setion section---1 map-section light">
        <Map img="./map-light.svg" />
      </section>
      <section className="section-11 query-form">
        <div className="form-head-title bg-grey">
          <div className="container">
            <div className="col-12 text-center">
              <h2 className="heading">Have a query? Talk to us</h2>
              <p>
                If you would like to know more about our Solar services please
                feel free shoot us a message using this web form.
              </p>
            </div>
          </div>
        </div>
        <div className="container form-container">
          <Queryform />
        </div>
      </section>
      <Footer />
    </div>
  );
}

export default Product;
