import React, { useEffect } from "react";
import Head from "next/head";
import Header from "./shared/header";
import Footer from "./shared/Footer";
import Queryform from "./shared/Queryform";
import { IoIosArrowUp } from "react-icons/io";

function SolarDesignPrice() {
  useEffect(() => {
    const accFaq = document.querySelectorAll(".faq-accordian");
    console.log(accFaq);
    for (let i = 0; i < accFaq.length; i++) {
      accFaq[i].addEventListener("click", function () {
        accFaq.forEach((accFaq) => {
          accFaq.classList.remove("active");
        });
        this.classList.toggle("active");
      });
    }
  }, []);
  return (
    <div className="services secondary-page container-fluid px-0 faq">
      <Head>
        <title>Faq</title>
        <meta
          name="description"
          content="Generated by create next app shubham"
        />
        <link
          rel="preload"
          href="../../../public/fonts/GTWalsheimPro-Regular.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Header />
      <section className="section section---1 faq-page bg-grey">
        <div className="service-heading container">
          <h1 className="center-heading heading">Frequently Asked Question</h1>
          <p className="center-heading col-lg-5 col-11 mx-auto mb-3">
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum
          </p>
        </div>
        <div className="faq-content container">
          <div className="faq-page__parent d-flex">
            <div className="d-flex faq-container">
              <div className="container__list col-lg-6 col-12">
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>What Service does Wattmonk provide?</h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      Wattmonk caters to Solar professionals, including EPC&apos;s,
                      developers, dealers, and installers, providing everything
                      from customer pitching to PE stamps. These include Prelim
                      Designs (Solar Shade analysis, Sales proposals), Survey
                      features, Permit Design & PE stamping
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>What type of projects does Wattmonk handle?</h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      Wattmonk handles residential & commercial projects,
                      including rooftop, ground mount & carports.
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>How does Wattmonk solar installer&apos;s lives better?</h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>Wattmonk helps reduce design costs by up to 50%.</p>
                    <ul className="mt-3">
                      <li className="mb-2">
                        <p>
                          Improve Delivery timelines (Get designs in hours, not
                          in days)
                        </p>
                      </li>
                      <li className="mb-2">
                        <p>
                          Execute a 3 step Quality assurance process on each
                          design before we deliver it
                        </p>
                      </li>
                      <li className="mb-2">
                        <p>
                          We are available 24x7 with more than 100 designers on
                          our payroll
                        </p>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>
                      What is the typical turnaround time for each Solar
                      project?
                    </h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      Wattmonk can deliver all residential projects as per the
                      below table.
                    </p>
                    <table
                      className="mt-3 mb-3"
                      style={{ width: "100%", fontSize: "14px" }}
                    >
                      <tr
                        style={{ background: "#f3b847", textAlign: "center" }}
                      >
                        <th className="col-1">Sr. no</th>
                        <th className="col-5">Services</th>
                        <th className="col-6">
                          For residential Turn-Around Time
                        </th>
                      </tr>
                      <tr>
                        <td className="text-center">1</td>
                        <td>Site Assessment (Shade Analysis)</td>
                        <td className="text-center">1 hr</td>
                      </tr>

                      <tr>
                        <td className="text-center">2</td>
                        <td>Solar Sales Proposal</td>
                        <td className="text-center">3 hrs</td>
                      </tr>
                      <tr>
                        <td className="text-center">3</td>
                        <td>Permit Design (PV)</td>
                        <td className="pb-3 pt-3 text-center" rowSpan={3}>
                          All order recieved before 12 noon EST will be
                          delivered same day, rest by next day morning(Avg
                          delivery time 12 hours)
                        </td>
                      </tr>
                      <tr>
                        <td className="text-center">4</td>
                        <td>Permit Design (Battery)</td>
                      </tr>
                      <tr>
                        <td className="text-center">5</td>
                        <td>Permit Design (PV + Battery)</td>
                      </tr>
                      <tr>
                        <td className="text-center">6</td>
                        <td>PE Stamp (Structural)</td>
                        <td className="text-center">12-24 hrs</td>
                      </tr>
                      <tr>
                        <td className="text-center">7</td>
                        <td>PE Stamp (Electrical)</td>
                        <td className="text-center">upto 48 hrs</td>
                      </tr>
                    </table>
                    <p className="mt-3">
                      For commercial projects, times vary depending on projects
                      size (in KW)
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>Wattmonk average capacity to handle each month?</h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      As of date (May 2021), Wattmonk delivers 25MW of solar
                      projects every month
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>
                      How does the Wattmonk platform help solar installers?
                    </h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      Wattmonk platform provides installers ease to access their
                      solar projects on the go.
                    </p>
                    <ul className="mt-3">
                      <li className="mb-2">
                        <p>
                          24x7 backend support with Text, Audio, Video platform
                        </p>
                      </li>
                      <li className="mb-2">
                        <p>
                          In-house, IT team to integrate our platform with your
                          software (API integration)
                        </p>
                      </li>
                      <li className="mb-2">
                        <p>
                          Suggestive solar site survey application to capture
                          all critical data
                        </p>
                      </li>
                      <li className="mb-2">
                        <p>Real-time status update for each solar project</p>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>Can Permit designs be customized for our AHJs?</h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      All of our permit designs are open to customization basis
                      AHJs and Installer needs
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>What PE services are provided by Wattmonk?</h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      Both Electrical and structural stamps can be obtained
                      through Wattmonk.
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>
                      What is Wattmonk&apos;s average success rate for AHJs
                      acceptance across the US
                    </h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>We have a 98.3% % success rate across AHJs</p>
                  </div>
                </div>
              </div>
              <div className="container__list col-lg-6 col-12">
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>
                      Does Wattmonk support any revisions based on AHJs
                      feedback?
                    </h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      We provide free-of-cost modification/edits on existing
                      Permit designs.
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>
                      TWhat types of Permit designs does Wattmonk provide?
                    </h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>We can provide all types of permits for:</p>
                    <ul className="mt-3">
                      <li className="mb-2">
                        <p>Photovoltaic (PV)</p>
                      </li>
                      <li className="mb-2">
                        <p>PV + Storage/ Battery</p>
                      </li>
                      <li className="mb-2">
                        <p>Battery Only</p>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>
                      What type of line diagrams are provided by Wattmonk for
                      each solar project?
                    </h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      We compete in both Single line & three-line diagrams for
                      Solar projects
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>How do you signup on the platform?</h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      It&apos;s simple, visit https://admin.wattmonk.com and register
                      for free.
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>What platforms are Wattmonk solar tools available?</h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      Our Solar design tool can be accessed on all online
                      browsers along with Android and iOS users.
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>
                      How much time does it take to order any services with
                      Wattmonk
                    </h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      5 minutes to place an order with us using its solar design
                      platform/ Tool.
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>Why is PE Stamping so critical?</h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      A PE Stamp demonstrates a professional engineer&apos;s
                      approval.
                    </p>
                    <ul className="mt-3">
                      <li className="mb-2">
                        <p>
                          PE stamps verify that the system will perform as per
                          guidelines
                        </p>
                      </li>
                      <li className="mb-2">
                        <p>
                          There are many cases where a project requires
                          government approval, and a PE stamp can prove
                          legitimacy.
                        </p>
                      </li>
                      <li className="mb-2">
                        <p>
                          The PE Stamp says that the engineer is responsible for
                          the system&apos;s integrity and the lives affected by their
                          work.
                        </p>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>
                      What sales proposal designs can be used by Wattmonk to
                      create a Permit Package?
                    </h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      Wattmonk is well equipped to handle various solar design
                      outputs, such as Aurora solar, Helioscope, Solo, and more.
                    </p>
                  </div>
                </div>
                <div className="faq-accordian simple-shadow">
                  <div className="faq-accordian__head">
                    <h4>
                      What information does Wattmonk require for a stand-alone
                      permit design order?
                    </h4>
                    <span>
                      <IoIosArrowUp />
                    </span>
                  </div>
                  <div className="faq-accordian__body">
                    <p>
                      All of the basic information pertaining to the property is
                      required. These include Customer approved sales proposal,
                      Site survey images including any obstacles, Intake form
                      for Utility details, and AHJ codes.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="section section---2 bg-grey">
        <div className="service-heading container">
          <h1 className="center-heading heading">Still have a Question?</h1>
          <p className="center-heading col-lg-5 col-11 mx-auto mb-3">
            If you cannot find answer to your question in our FAQ, you can
            always contact us. We will answer to you shortly!
          </p>
        </div>
        <div className="container form-container">
          <Queryform />
        </div>
      </section>
      <Footer />
    </div>
  );
}

export default SolarDesignPrice;
