import React, { useEffect } from "react";
import Head from "next/head";
import Header from "./shared/header";
import Footer from "./shared/Footer";
function Product() {
  return (
    <div className="container-fluid px-0 media">
      <Head>
        <title>Media</title>
        <meta
          name="description"
          content="Generated by create next app shubham"
        />
        <link
          rel="preload"
          href="../../../public/fonts/GTWalsheimPro-Regular.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Header />
      <section className="section container">
        <div className="service-heading ">
          <h1 className="center-heading heading">Movers and Shakers</h1>
          <p className="center-heading col-lg-9 col-11 mx-auto mb-3">
            To address the global energy crisis and moving towards clean energy,
            solar is often cited as one of the top technologies to harness
            energy. However, over the years, the adoption of rooftop solar,
            especially in the residential segment, has been at best lukewarm.
          </p>
          <p className="center-heading col-lg-9 col-11 mx-auto mb-3">
            Call it long ROI, high upfront costs, cumbersome procurement or
            technological complexity - whatever the reasons babe, residential
            customers have always been reluctant to put solar on their rooftops.
          </p>
          <p className="center-heading col-lg-9 col-11 mx-auto mb-3">
            Here is a company that endeavors to change that. Based out of
            Singapore, we spoke to Ankit Sheoran from Wattmonk Technologies to
            get his perspective and vision on the industry
          </p>
        </div>
        <div className="showcase col-12">
          <img src="/ankit-heoran.JPG" alt="ankit sheron" />
        </div>
      </section>
      <Footer />
    </div>
  );
}

export default Product;
