import React, { useEffect } from "react";
import Head from "next/head";
import Header from "./shared/header";
import Footer from "./shared/Footer";
import Commingsoon from "./shared/Commingsoon";
function Product() {
  return (
    <div className="container-fluid px-0">
      <Head>
        <title>Solar Permit Package</title>
        <meta
          name="description"
          content="Generated by create next app shubham"
        />
        <link
          rel="preload"
          href="../../../public/fonts/GTWalsheimPro-Regular.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Header />
      <Commingsoon />
      <Footer />
    </div>
  );
}

export default Product;
